const fs = require('fs');
const path = require('path');

const srcDir = path.join(__dirname, 'photos');
const destDir = path.join(__dirname, 'public', 'photos');

// Create destination directory if it doesn't exist
if (!fs.existsSync(destDir)) {
  fs.mkdirSync(destDir, { recursive: true });
}

console.log('Copying files from', srcDir, 'to', destDir);

// Read files from srcDir
const files = fs.readdirSync(srcDir);
const imageExtensions = ['.jpg', '.jpeg', '.png', '.webp', '.gif'];
const videoExtensions = ['.mp4', '.mov', '.webm'];

const images = [];
const videos = [];

// Deterministic hash function to make assignments consistent
function getHash(str) {
  let hash = 0;
  for (let i = 0; i < str.length; i++) {
    hash = str.charCodeAt(i) + ((hash << 5) - hash);
  }
  return Math.abs(hash);
}

const devices = ['Samsung Galaxy S24 Ultra', 'Samsung Galaxy S21 FE'];
const categories = ['Nature', 'Cityscape', 'Everyday Life', 'Low Light'];

files.forEach(file => {
  const ext = path.extname(file).toLowerCase();
  const srcPath = path.join(srcDir, file);
  const destPath = path.join(destDir, file);
  
  // Copy file
  fs.copyFileSync(srcPath, destPath);
  
  // Public path
  const publicPath = `/photos/${encodeURIComponent(file)}`;
  
  // Generate deterministic details based on filename hash
  const hashVal = getHash(file);
  const device = devices[hashVal % devices.length];
  const category = categories[hashVal % categories.length];
  
  // Create readable title from WhatsApp name if possible, or generic
  // WhatsApp name has format "WhatsApp Image 2026-07-16 at 5.59.31 PM (1).jpeg"
  // Let's create a beautiful generic title like "Moment #HASH", or "Visual Story"
  const title = `Capture #${hashVal % 1000}`;
  
  if (imageExtensions.includes(ext)) {
    images.push({
      src: publicPath,
      name: file,
      title: title,
      device: device,
      category: category
    });
  } else if (videoExtensions.includes(ext)) {
    let aspectRatio = 'landscape';
    try {
      const buffer = fs.readFileSync(srcPath);
      const tkhdOffset = buffer.indexOf(Buffer.from('tkhd'));
      if (tkhdOffset !== -1) {
        const version = buffer.readUInt8(tkhdOffset + 4);
        let widthOffset, heightOffset;
        if (version === 0) {
          widthOffset = tkhdOffset + 80;
          heightOffset = tkhdOffset + 84;
        } else if (version === 1) {
          widthOffset = tkhdOffset + 96;
          heightOffset = tkhdOffset + 100;
        }
        if (widthOffset && heightOffset && widthOffset + 8 <= buffer.length) {
          const width = buffer.readUInt32BE(widthOffset) >> 16;
          const height = buffer.readUInt32BE(heightOffset) >> 16;
          if (height > width) {
            aspectRatio = 'portrait';
          }
        }
      }
    } catch (err) {
      console.error(`Error reading video dimensions for ${file}:`, err.message);
    }

    let titleNum = hashVal % 100;
    if (titleNum === 86) {
      titleNum = 81;
    }

    videos.push({
      src: publicPath,
      name: file,
      title: `Moment Reel #${titleNum}`,
      device: device,
      category: category,
      aspectRatio: aspectRatio
    });
  }
});

console.log(`Copied ${images.length} images and ${videos.length} videos.`);

// Generate TS file
const tsContent = `// This file is auto-generated by copy-media.js
export interface MediaImage {
  src: string;
  name: string;
  title: string;
  device: string;
  category: string;
}

export interface MediaVideo {
  src: string;
  name: string;
  title: string;
  device: string;
  category: string;
  aspectRatio: 'landscape' | 'portrait';
}

export const localImages: MediaImage[] = ${JSON.stringify(images, null, 2)};

export const localVideos: MediaVideo[] = ${JSON.stringify(videos, null, 2)};
`;

fs.writeFileSync(path.join(__dirname, 'src', 'data', 'mediaData.ts'), tsContent);
console.log('Generated src/data/mediaData.ts');
