// This file is auto-generated by copy-media.js
export interface MediaImage {
  src: string;
  name: string;
  title: string;
  device: string;
  category: string;
}

export interface MediaVideo {
  src: string;
  name: string;
  title: string;
  device: string;
  category: string;
  aspectRatio: 'landscape' | 'portrait';
}

export const localImages: MediaImage[] = [
  {
    "src": "/photos/WhatsApp%20Image%202026-07-16%20at%205.59.31%20PM%20(1).jpeg",
    "name": "WhatsApp Image 2026-07-16 at 5.59.31 PM (1).jpeg",
    "title": "Capture #240",
    "device": "Samsung Galaxy S24 Ultra",
    "category": "Nature"
  },
  {
    "src": "/photos/WhatsApp%20Image%202026-07-16%20at%205.59.31%20PM.jpeg",
    "name": "WhatsApp Image 2026-07-16 at 5.59.31 PM.jpeg",
    "title": "Capture #776",
    "device": "Samsung Galaxy S24 Ultra",
    "category": "Nature"
  },
  {
    "src": "/photos/WhatsApp%20Image%202026-07-16%20at%205.59.35%20PM.jpeg",
    "name": "WhatsApp Image 2026-07-16 at 5.59.35 PM.jpeg",
    "title": "Capture #220",
    "device": "Samsung Galaxy S24 Ultra",
    "category": "Nature"
  },
  {
    "src": "/photos/WhatsApp%20Image%202026-07-16%20at%205.59.41%20PM%20(1).jpeg",
    "name": "WhatsApp Image 2026-07-16 at 5.59.41 PM (1).jpeg",
    "title": "Capture #319",
    "device": "Samsung Galaxy S21 FE",
    "category": "Low Light"
  },
  {
    "src": "/photos/WhatsApp%20Image%202026-07-16%20at%205.59.41%20PM%20(2).jpeg",
    "name": "WhatsApp Image 2026-07-16 at 5.59.41 PM (2).jpeg",
    "title": "Capture #0",
    "device": "Samsung Galaxy S24 Ultra",
    "category": "Nature"
  },
  {
    "src": "/photos/WhatsApp%20Image%202026-07-16%20at%205.59.41%20PM.jpeg",
    "name": "WhatsApp Image 2026-07-16 at 5.59.41 PM.jpeg",
    "title": "Capture #975",
    "device": "Samsung Galaxy S21 FE",
    "category": "Low Light"
  },
  {
    "src": "/photos/WhatsApp%20Image%202026-07-16%20at%205.59.42%20PM%20(1).jpeg",
    "name": "WhatsApp Image 2026-07-16 at 5.59.42 PM (1).jpeg",
    "title": "Capture #312",
    "device": "Samsung Galaxy S24 Ultra",
    "category": "Nature"
  },
  {
    "src": "/photos/WhatsApp%20Image%202026-07-16%20at%205.59.42%20PM%20(2).jpeg",
    "name": "WhatsApp Image 2026-07-16 at 5.59.42 PM (2).jpeg",
    "title": "Capture #993",
    "device": "Samsung Galaxy S21 FE",
    "category": "Cityscape"
  },
  {
    "src": "/photos/WhatsApp%20Image%202026-07-16%20at%205.59.42%20PM%20(3).jpeg",
    "name": "WhatsApp Image 2026-07-16 at 5.59.42 PM (3).jpeg",
    "title": "Capture #674",
    "device": "Samsung Galaxy S24 Ultra",
    "category": "Everyday Life"
  },
  {
    "src": "/photos/WhatsApp%20Image%202026-07-16%20at%205.59.42%20PM.jpeg",
    "name": "WhatsApp Image 2026-07-16 at 5.59.42 PM.jpeg",
    "title": "Capture #512",
    "device": "Samsung Galaxy S24 Ultra",
    "category": "Nature"
  },
  {
    "src": "/photos/WhatsApp%20Image%202026-07-16%20at%205.59.43%20PM.jpeg",
    "name": "WhatsApp Image 2026-07-16 at 5.59.43 PM.jpeg",
    "title": "Capture #345",
    "device": "Samsung Galaxy S21 FE",
    "category": "Cityscape"
  },
  {
    "src": "/photos/WhatsApp%20Image%202026-07-16%20at%205.59.44%20PM%20(1).jpeg",
    "name": "WhatsApp Image 2026-07-16 at 5.59.44 PM (1).jpeg",
    "title": "Capture #298",
    "device": "Samsung Galaxy S24 Ultra",
    "category": "Everyday Life"
  },
  {
    "src": "/photos/WhatsApp%20Image%202026-07-16%20at%205.59.44%20PM.jpeg",
    "name": "WhatsApp Image 2026-07-16 at 5.59.44 PM.jpeg",
    "title": "Capture #882",
    "device": "Samsung Galaxy S24 Ultra",
    "category": "Everyday Life"
  },
  {
    "src": "/photos/WhatsApp%20Image%202026-07-16%20at%205.59.45%20PM.jpeg",
    "name": "WhatsApp Image 2026-07-16 at 5.59.45 PM.jpeg",
    "title": "Capture #419",
    "device": "Samsung Galaxy S21 FE",
    "category": "Low Light"
  },
  {
    "src": "/photos/WhatsApp%20Image%202026-07-16%20at%205.59.56%20PM.jpeg",
    "name": "WhatsApp Image 2026-07-16 at 5.59.56 PM.jpeg",
    "title": "Capture #43",
    "device": "Samsung Galaxy S21 FE",
    "category": "Low Light"
  },
  {
    "src": "/photos/WhatsApp%20Image%202026-07-16%20at%205.59.57%20PM.jpeg",
    "name": "WhatsApp Image 2026-07-16 at 5.59.57 PM.jpeg",
    "title": "Capture #284",
    "device": "Samsung Galaxy S24 Ultra",
    "category": "Nature"
  },
  {
    "src": "/photos/WhatsApp%20Image%202026-07-16%20at%205.59.58%20PM%20(1).jpeg",
    "name": "WhatsApp Image 2026-07-16 at 5.59.58 PM (1).jpeg",
    "title": "Capture #941",
    "device": "Samsung Galaxy S21 FE",
    "category": "Cityscape"
  },
  {
    "src": "/photos/WhatsApp%20Image%202026-07-16%20at%205.59.58%20PM.jpeg",
    "name": "WhatsApp Image 2026-07-16 at 5.59.58 PM.jpeg",
    "title": "Capture #117",
    "device": "Samsung Galaxy S21 FE",
    "category": "Cityscape"
  },
  {
    "src": "/photos/WhatsApp%20Image%202026-07-16%20at%206.00.05%20PM%20(1).jpeg",
    "name": "WhatsApp Image 2026-07-16 at 6.00.05 PM (1).jpeg",
    "title": "Capture #28",
    "device": "Samsung Galaxy S24 Ultra",
    "category": "Nature"
  },
  {
    "src": "/photos/WhatsApp%20Image%202026-07-16%20at%206.00.05%20PM.jpeg",
    "name": "WhatsApp Image 2026-07-16 at 6.00.05 PM.jpeg",
    "title": "Capture #812",
    "device": "Samsung Galaxy S24 Ultra",
    "category": "Nature"
  },
  {
    "src": "/photos/WhatsApp%20Image%202026-07-16%20at%206.00.06%20PM.jpeg",
    "name": "WhatsApp Image 2026-07-16 at 6.00.06 PM.jpeg",
    "title": "Capture #645",
    "device": "Samsung Galaxy S21 FE",
    "category": "Cityscape"
  },
  {
    "src": "/photos/WhatsApp%20Image%202026-07-16%20at%206.00.07%20PM.jpeg",
    "name": "WhatsApp Image 2026-07-16 at 6.00.07 PM.jpeg",
    "title": "Capture #182",
    "device": "Samsung Galaxy S24 Ultra",
    "category": "Everyday Life"
  },
  {
    "src": "/photos/WhatsApp%20Image%202026-07-16%20at%206.00.08%20PM%20(1).jpeg",
    "name": "WhatsApp Image 2026-07-16 at 6.00.08 PM (1).jpeg",
    "title": "Capture #303",
    "device": "Samsung Galaxy S21 FE",
    "category": "Low Light"
  },
  {
    "src": "/photos/WhatsApp%20Image%202026-07-16%20at%206.00.08%20PM.jpeg",
    "name": "WhatsApp Image 2026-07-16 at 6.00.08 PM.jpeg",
    "title": "Capture #15",
    "device": "Samsung Galaxy S21 FE",
    "category": "Low Light"
  },
  {
    "src": "/photos/WhatsApp%20Image%202026-07-16%20at%206.00.09%20PM%20(1).jpeg",
    "name": "WhatsApp Image 2026-07-16 at 6.00.09 PM (1).jpeg",
    "title": "Capture #296",
    "device": "Samsung Galaxy S24 Ultra",
    "category": "Nature"
  },
  {
    "src": "/photos/WhatsApp%20Image%202026-07-16%20at%206.00.09%20PM%20(2).jpeg",
    "name": "WhatsApp Image 2026-07-16 at 6.00.09 PM (2).jpeg",
    "title": "Capture #977",
    "device": "Samsung Galaxy S21 FE",
    "category": "Cityscape"
  },
  {
    "src": "/photos/WhatsApp%20Image%202026-07-16%20at%206.00.09%20PM.jpeg",
    "name": "WhatsApp Image 2026-07-16 at 6.00.09 PM.jpeg",
    "title": "Capture #552",
    "device": "Samsung Galaxy S24 Ultra",
    "category": "Nature"
  },
  {
    "src": "/photos/WhatsApp%20Image%202026-07-16%20at%206.00.10%20PM%20(1).jpeg",
    "name": "WhatsApp Image 2026-07-16 at 6.00.10 PM (1).jpeg",
    "title": "Capture #734",
    "device": "Samsung Galaxy S24 Ultra",
    "category": "Everyday Life"
  },
  {
    "src": "/photos/WhatsApp%20Image%202026-07-16%20at%206.00.10%20PM.jpeg",
    "name": "WhatsApp Image 2026-07-16 at 6.00.10 PM.jpeg",
    "title": "Capture #326",
    "device": "Samsung Galaxy S24 Ultra",
    "category": "Everyday Life"
  },
  {
    "src": "/photos/WhatsApp%20Image%202026-07-16%20at%206.00.11%20PM%20(1).jpeg",
    "name": "WhatsApp Image 2026-07-16 at 6.00.11 PM (1).jpeg",
    "title": "Capture #23",
    "device": "Samsung Galaxy S21 FE",
    "category": "Low Light"
  },
  {
    "src": "/photos/WhatsApp%20Image%202026-07-16%20at%206.00.11%20PM%20(2).jpeg",
    "name": "WhatsApp Image 2026-07-16 at 6.00.11 PM (2).jpeg",
    "title": "Capture #704",
    "device": "Samsung Galaxy S24 Ultra",
    "category": "Nature"
  },
  {
    "src": "/photos/WhatsApp%20Image%202026-07-16%20at%206.00.11%20PM%20(3).jpeg",
    "name": "WhatsApp Image 2026-07-16 at 6.00.11 PM (3).jpeg",
    "title": "Capture #385",
    "device": "Samsung Galaxy S21 FE",
    "category": "Cityscape"
  },
  {
    "src": "/photos/WhatsApp%20Image%202026-07-16%20at%206.00.11%20PM.jpeg",
    "name": "WhatsApp Image 2026-07-16 at 6.00.11 PM.jpeg",
    "title": "Capture #159",
    "device": "Samsung Galaxy S21 FE",
    "category": "Low Light"
  },
  {
    "src": "/photos/WhatsApp%20Image%202026-07-16%20at%206.00.12%20PM.jpeg",
    "name": "WhatsApp Image 2026-07-16 at 6.00.12 PM.jpeg",
    "title": "Capture #400",
    "device": "Samsung Galaxy S24 Ultra",
    "category": "Nature"
  },
  {
    "src": "/photos/WhatsApp%20Image%202026-07-16%20at%206.00.30%20PM.jpeg",
    "name": "WhatsApp Image 2026-07-16 at 6.00.30 PM.jpeg",
    "title": "Capture #316",
    "device": "Samsung Galaxy S24 Ultra",
    "category": "Nature"
  },
  {
    "src": "/photos/WhatsApp%20Image%202026-07-16%20at%206.00.31%20PM%20(1).jpeg",
    "name": "WhatsApp Image 2026-07-16 at 6.00.31 PM (1).jpeg",
    "title": "Capture #477",
    "device": "Samsung Galaxy S21 FE",
    "category": "Cityscape"
  },
  {
    "src": "/photos/WhatsApp%20Image%202026-07-16%20at%206.00.31%20PM%20(2).jpeg",
    "name": "WhatsApp Image 2026-07-16 at 6.00.31 PM (2).jpeg",
    "title": "Capture #862",
    "device": "Samsung Galaxy S24 Ultra",
    "category": "Everyday Life"
  },
  {
    "src": "/photos/WhatsApp%20Image%202026-07-16%20at%206.00.31%20PM.jpeg",
    "name": "WhatsApp Image 2026-07-16 at 6.00.31 PM.jpeg",
    "title": "Capture #557",
    "device": "Samsung Galaxy S21 FE",
    "category": "Cityscape"
  },
  {
    "src": "/photos/WhatsApp%20Image%202026-07-16%20at%206.18.50%20PM.jpeg",
    "name": "WhatsApp Image 2026-07-16 at 6.18.50 PM.jpeg",
    "title": "Capture #51",
    "device": "Samsung Galaxy S21 FE",
    "category": "Low Light"
  },
  {
    "src": "/photos/WhatsApp%20Image%202026-07-16%20at%206.18.53%20PM%20(1).jpeg",
    "name": "WhatsApp Image 2026-07-16 at 6.18.53 PM (1).jpeg",
    "title": "Capture #86",
    "device": "Samsung Galaxy S24 Ultra",
    "category": "Everyday Life"
  },
  {
    "src": "/photos/WhatsApp%20Image%202026-07-16%20at%206.18.53%20PM.jpeg",
    "name": "WhatsApp Image 2026-07-16 at 6.18.53 PM.jpeg",
    "title": "Capture #958",
    "device": "Samsung Galaxy S24 Ultra",
    "category": "Everyday Life"
  },
  {
    "src": "/photos/WhatsApp%20Image%202026-07-16%20at%206.19.00%20PM.jpeg",
    "name": "WhatsApp Image 2026-07-16 at 6.19.00 PM.jpeg",
    "title": "Capture #703",
    "device": "Samsung Galaxy S21 FE",
    "category": "Low Light"
  },
  {
    "src": "/photos/WhatsApp%20Image%202026-07-16%20at%206.19.01%20PM%20(1).jpeg",
    "name": "WhatsApp Image 2026-07-16 at 6.19.01 PM (1).jpeg",
    "title": "Capture #456",
    "device": "Samsung Galaxy S24 Ultra",
    "category": "Nature"
  },
  {
    "src": "/photos/WhatsApp%20Image%202026-07-16%20at%206.19.01%20PM.jpeg",
    "name": "WhatsApp Image 2026-07-16 at 6.19.01 PM.jpeg",
    "title": "Capture #536",
    "device": "Samsung Galaxy S24 Ultra",
    "category": "Nature"
  },
  {
    "src": "/photos/WhatsApp%20Image%202026-07-16%20at%206.19.04%20PM%20(1).jpeg",
    "name": "WhatsApp Image 2026-07-16 at 6.19.04 PM (1).jpeg",
    "title": "Capture #435",
    "device": "Samsung Galaxy S21 FE",
    "category": "Low Light"
  },
  {
    "src": "/photos/WhatsApp%20Image%202026-07-16%20at%206.19.04%20PM.jpeg",
    "name": "WhatsApp Image 2026-07-16 at 6.19.04 PM.jpeg",
    "title": "Capture #443",
    "device": "Samsung Galaxy S21 FE",
    "category": "Low Light"
  },
  {
    "src": "/photos/WhatsApp%20Image%202026-07-16%20at%206.19.12%20PM.jpeg",
    "name": "WhatsApp Image 2026-07-16 at 6.19.12 PM.jpeg",
    "title": "Capture #864",
    "device": "Samsung Galaxy S24 Ultra",
    "category": "Nature"
  },
  {
    "src": "/photos/WhatsApp%20Image%202026-07-16%20at%206.19.13%20PM%20(1).jpeg",
    "name": "WhatsApp Image 2026-07-16 at 6.19.13 PM (1).jpeg",
    "title": "Capture #113",
    "device": "Samsung Galaxy S21 FE",
    "category": "Cityscape"
  },
  {
    "src": "/photos/WhatsApp%20Image%202026-07-16%20at%206.19.13%20PM%20(2).jpeg",
    "name": "WhatsApp Image 2026-07-16 at 6.19.13 PM (2).jpeg",
    "title": "Capture #794",
    "device": "Samsung Galaxy S24 Ultra",
    "category": "Everyday Life"
  },
  {
    "src": "/photos/WhatsApp%20Image%202026-07-16%20at%206.19.13%20PM.jpeg",
    "name": "WhatsApp Image 2026-07-16 at 6.19.13 PM.jpeg",
    "title": "Capture #401",
    "device": "Samsung Galaxy S21 FE",
    "category": "Cityscape"
  },
  {
    "src": "/photos/WhatsApp%20Image%202026-07-16%20at%206.19.14%20PM%20(1).jpeg",
    "name": "WhatsApp Image 2026-07-16 at 6.19.14 PM (1).jpeg",
    "title": "Capture #106",
    "device": "Samsung Galaxy S24 Ultra",
    "category": "Everyday Life"
  },
  {
    "src": "/photos/WhatsApp%20Image%202026-07-16%20at%206.19.14%20PM.jpeg",
    "name": "WhatsApp Image 2026-07-16 at 6.19.14 PM.jpeg",
    "title": "Capture #234",
    "device": "Samsung Galaxy S24 Ultra",
    "category": "Everyday Life"
  },
  {
    "src": "/photos/WhatsApp%20Image%202026-07-16%20at%206.19.15%20PM%20(1).jpeg",
    "name": "WhatsApp Image 2026-07-16 at 6.19.15 PM (1).jpeg",
    "title": "Capture #803",
    "device": "Samsung Galaxy S21 FE",
    "category": "Low Light"
  },
  {
    "src": "/photos/WhatsApp%20Image%202026-07-16%20at%206.19.15%20PM%20(2).jpeg",
    "name": "WhatsApp Image 2026-07-16 at 6.19.15 PM (2).jpeg",
    "title": "Capture #484",
    "device": "Samsung Galaxy S24 Ultra",
    "category": "Nature"
  },
  {
    "src": "/photos/WhatsApp%20Image%202026-07-16%20at%206.19.15%20PM.jpeg",
    "name": "WhatsApp Image 2026-07-16 at 6.19.15 PM.jpeg",
    "title": "Capture #475",
    "device": "Samsung Galaxy S21 FE",
    "category": "Low Light"
  },
  {
    "src": "/photos/WhatsApp%20Image%202026-07-16%20at%206.19.16%20PM%20(1).jpeg",
    "name": "WhatsApp Image 2026-07-16 at 6.19.16 PM (1).jpeg",
    "title": "Capture #796",
    "device": "Samsung Galaxy S24 Ultra",
    "category": "Nature"
  },
  {
    "src": "/photos/WhatsApp%20Image%202026-07-16%20at%206.19.16%20PM%20(2).jpeg",
    "name": "WhatsApp Image 2026-07-16 at 6.19.16 PM (2).jpeg",
    "title": "Capture #477",
    "device": "Samsung Galaxy S21 FE",
    "category": "Cityscape"
  },
  {
    "src": "/photos/WhatsApp%20Image%202026-07-16%20at%206.19.16%20PM%20(3).jpeg",
    "name": "WhatsApp Image 2026-07-16 at 6.19.16 PM (3).jpeg",
    "title": "Capture #158",
    "device": "Samsung Galaxy S24 Ultra",
    "category": "Everyday Life"
  },
  {
    "src": "/photos/WhatsApp%20Image%202026-07-16%20at%206.19.16%20PM.jpeg",
    "name": "WhatsApp Image 2026-07-16 at 6.19.16 PM.jpeg",
    "title": "Capture #308",
    "device": "Samsung Galaxy S24 Ultra",
    "category": "Nature"
  },
  {
    "src": "/photos/WhatsApp%20Image%202026-07-16%20at%206.19.17%20PM%20(1).jpeg",
    "name": "WhatsApp Image 2026-07-16 at 6.19.17 PM (1).jpeg",
    "title": "Capture #85",
    "device": "Samsung Galaxy S21 FE",
    "category": "Cityscape"
  },
  {
    "src": "/photos/WhatsApp%20Image%202026-07-16%20at%206.19.17%20PM.jpeg",
    "name": "WhatsApp Image 2026-07-16 at 6.19.17 PM.jpeg",
    "title": "Capture #141",
    "device": "Samsung Galaxy S21 FE",
    "category": "Cityscape"
  },
  {
    "src": "/photos/WhatsApp%20Image%202026-07-16%20at%206.19.18%20PM%20(1).jpeg",
    "name": "WhatsApp Image 2026-07-16 at 6.19.18 PM (1).jpeg",
    "title": "Capture #782",
    "device": "Samsung Galaxy S24 Ultra",
    "category": "Everyday Life"
  },
  {
    "src": "/photos/WhatsApp%20Image%202026-07-16%20at%206.19.18%20PM%20(2).jpeg",
    "name": "WhatsApp Image 2026-07-16 at 6.19.18 PM (2).jpeg",
    "title": "Capture #463",
    "device": "Samsung Galaxy S21 FE",
    "category": "Low Light"
  },
  {
    "src": "/photos/WhatsApp%20Image%202026-07-16%20at%206.19.18%20PM%20(3).jpeg",
    "name": "WhatsApp Image 2026-07-16 at 6.19.18 PM (3).jpeg",
    "title": "Capture #144",
    "device": "Samsung Galaxy S24 Ultra",
    "category": "Nature"
  },
  {
    "src": "/photos/WhatsApp%20Image%202026-07-16%20at%206.19.18%20PM.jpeg",
    "name": "WhatsApp Image 2026-07-16 at 6.19.18 PM.jpeg",
    "title": "Capture #678",
    "device": "Samsung Galaxy S24 Ultra",
    "category": "Everyday Life"
  },
  {
    "src": "/photos/WhatsApp%20Image%202026-07-16%20at%206.19.19%20PM%20(1).jpeg",
    "name": "WhatsApp Image 2026-07-16 at 6.19.19 PM (1).jpeg",
    "title": "Capture #71",
    "device": "Samsung Galaxy S21 FE",
    "category": "Low Light"
  },
  {
    "src": "/photos/WhatsApp%20Image%202026-07-16%20at%206.19.19%20PM%20(2).jpeg",
    "name": "WhatsApp Image 2026-07-16 at 6.19.19 PM (2).jpeg",
    "title": "Capture #752",
    "device": "Samsung Galaxy S24 Ultra",
    "category": "Nature"
  },
  {
    "src": "/photos/WhatsApp%20Image%202026-07-16%20at%206.19.19%20PM%20(3).jpeg",
    "name": "WhatsApp Image 2026-07-16 at 6.19.19 PM (3).jpeg",
    "title": "Capture #433",
    "device": "Samsung Galaxy S21 FE",
    "category": "Cityscape"
  },
  {
    "src": "/photos/WhatsApp%20Image%202026-07-16%20at%206.19.19%20PM.jpeg",
    "name": "WhatsApp Image 2026-07-16 at 6.19.19 PM.jpeg",
    "title": "Capture #511",
    "device": "Samsung Galaxy S21 FE",
    "category": "Low Light"
  },
  {
    "src": "/photos/WhatsApp%20Image%202026-07-16%20at%206.19.20%20PM%20(1).jpeg",
    "name": "WhatsApp Image 2026-07-16 at 6.19.20 PM (1).jpeg",
    "title": "Capture #213",
    "device": "Samsung Galaxy S21 FE",
    "category": "Cityscape"
  },
  {
    "src": "/photos/WhatsApp%20Image%202026-07-16%20at%206.19.20%20PM%20(2).jpeg",
    "name": "WhatsApp Image 2026-07-16 at 6.19.20 PM (2).jpeg",
    "title": "Capture #894",
    "device": "Samsung Galaxy S24 Ultra",
    "category": "Everyday Life"
  },
  {
    "src": "/photos/WhatsApp%20Image%202026-07-16%20at%206.19.20%20PM.jpeg",
    "name": "WhatsApp Image 2026-07-16 at 6.19.20 PM.jpeg",
    "title": "Capture #693",
    "device": "Samsung Galaxy S21 FE",
    "category": "Cityscape"
  },
  {
    "src": "/photos/WhatsApp%20Image%202026-07-16%20at%206.19.21%20PM%20(1).jpeg",
    "name": "WhatsApp Image 2026-07-16 at 6.19.21 PM (1).jpeg",
    "title": "Capture #206",
    "device": "Samsung Galaxy S24 Ultra",
    "category": "Everyday Life"
  },
  {
    "src": "/photos/WhatsApp%20Image%202026-07-16%20at%206.19.21%20PM%20(2).jpeg",
    "name": "WhatsApp Image 2026-07-16 at 6.19.21 PM (2).jpeg",
    "title": "Capture #887",
    "device": "Samsung Galaxy S21 FE",
    "category": "Low Light"
  },
  {
    "src": "/photos/WhatsApp%20Image%202026-07-16%20at%206.19.21%20PM%20(3).jpeg",
    "name": "WhatsApp Image 2026-07-16 at 6.19.21 PM (3).jpeg",
    "title": "Capture #568",
    "device": "Samsung Galaxy S24 Ultra",
    "category": "Nature"
  },
  {
    "src": "/photos/WhatsApp%20Image%202026-07-16%20at%206.19.21%20PM.jpeg",
    "name": "WhatsApp Image 2026-07-16 at 6.19.21 PM.jpeg",
    "title": "Capture #526",
    "device": "Samsung Galaxy S24 Ultra",
    "category": "Everyday Life"
  }
];

export const localVideos: MediaVideo[] = [
  {
    "src": "/photos/WhatsApp%20Video%202026-07-16%20at%205.59.35%20PM.mp4",
    "name": "WhatsApp Video 2026-07-16 at 5.59.35 PM.mp4",
    "title": "Moment Reel #81",
    "device": "Samsung Galaxy S21 FE",
    "category": "Cityscape",
    "aspectRatio": "landscape"
  },
  {
    "src": "/photos/WhatsApp%20Video%202026-07-16%20at%205.59.40%20PM.mp4",
    "name": "WhatsApp Video 2026-07-16 at 5.59.40 PM.mp4",
    "title": "Moment Reel #65",
    "device": "Samsung Galaxy S21 FE",
    "category": "Cityscape",
    "aspectRatio": "landscape"
  },
  {
    "src": "/photos/WhatsApp%20Video%202026-07-16%20at%205.59.56%20PM.mp4",
    "name": "WhatsApp Video 2026-07-16 at 5.59.56 PM.mp4",
    "title": "Moment Reel #81",
    "device": "Samsung Galaxy S24 Ultra",
    "category": "Everyday Life",
    "aspectRatio": "portrait"
  },
  {
    "src": "/photos/WhatsApp%20Video%202026-07-16%20at%206.00.05%20PM.mp4",
    "name": "WhatsApp Video 2026-07-16 at 6.00.05 PM.mp4",
    "title": "Moment Reel #95",
    "device": "Samsung Galaxy S21 FE",
    "category": "Low Light",
    "aspectRatio": "portrait"
  },
  {
    "src": "/photos/WhatsApp%20Video%202026-07-16%20at%206.00.08%20PM.mp4",
    "name": "WhatsApp Video 2026-07-16 at 6.00.08 PM.mp4",
    "title": "Moment Reel #81",
    "device": "Samsung Galaxy S24 Ultra",
    "category": "Everyday Life",
    "aspectRatio": "portrait"
  },
  {
    "src": "/photos/WhatsApp%20Video%202026-07-16%20at%206.00.29%20PM.mp4",
    "name": "WhatsApp Video 2026-07-16 at 6.00.29 PM.mp4",
    "title": "Moment Reel #81",
    "device": "Samsung Galaxy S21 FE",
    "category": "Cityscape",
    "aspectRatio": "portrait"
  },
  {
    "src": "/photos/WhatsApp%20Video%202026-07-16%20at%206.19.00%20PM%20(1).mp4",
    "name": "WhatsApp Video 2026-07-16 at 6.19.00 PM (1).mp4",
    "title": "Moment Reel #38",
    "device": "Samsung Galaxy S24 Ultra",
    "category": "Everyday Life",
    "aspectRatio": "portrait"
  },
  {
    "src": "/photos/WhatsApp%20Video%202026-07-16%20at%206.19.00%20PM.mp4",
    "name": "WhatsApp Video 2026-07-16 at 6.19.00 PM.mp4",
    "title": "Moment Reel #90",
    "device": "Samsung Galaxy S24 Ultra",
    "category": "Everyday Life",
    "aspectRatio": "landscape"
  },
  {
    "src": "/photos/WhatsApp%20Video%202026-07-16%20at%206.19.12%20PM%20(1).mp4",
    "name": "WhatsApp Video 2026-07-16 at 6.19.12 PM (1).mp4",
    "title": "Moment Reel #27",
    "device": "Samsung Galaxy S21 FE",
    "category": "Low Light",
    "aspectRatio": "portrait"
  },
  {
    "src": "/photos/WhatsApp%20Video%202026-07-16%20at%206.19.12%20PM.mp4",
    "name": "WhatsApp Video 2026-07-16 at 6.19.12 PM.mp4",
    "title": "Moment Reel #99",
    "device": "Samsung Galaxy S21 FE",
    "category": "Low Light",
    "aspectRatio": "portrait"
  },
  {
    "src": "/photos/WhatsApp%20Video%202026-07-16%20at%206.19.13%20PM.mp4",
    "name": "WhatsApp Video 2026-07-16 at 6.19.13 PM.mp4",
    "title": "Moment Reel #60",
    "device": "Samsung Galaxy S24 Ultra",
    "category": "Nature",
    "aspectRatio": "portrait"
  },
  {
    "src": "/photos/WhatsApp%20Video%202026-07-16%20at%206.19.14%20PM.mp4",
    "name": "WhatsApp Video 2026-07-16 at 6.19.14 PM.mp4",
    "title": "Moment Reel #25",
    "device": "Samsung Galaxy S21 FE",
    "category": "Cityscape",
    "aspectRatio": "portrait"
  },
  {
    "src": "/photos/WhatsApp%20Video%202026-07-16%20at%206.19.15%20PM.mp4",
    "name": "WhatsApp Video 2026-07-16 at 6.19.15 PM.mp4",
    "title": "Moment Reel #81",
    "device": "Samsung Galaxy S24 Ultra",
    "category": "Everyday Life",
    "aspectRatio": "portrait"
  },
  {
    "src": "/photos/WhatsApp%20Video%202026-07-16%20at%206.19.17%20PM.mp4",
    "name": "WhatsApp Video 2026-07-16 at 6.19.17 PM.mp4",
    "title": "Moment Reel #16",
    "device": "Samsung Galaxy S24 Ultra",
    "category": "Nature",
    "aspectRatio": "portrait"
  }
];
